name: deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/readme.md"

env:
    VITE_BACKENDAPI_URL: ${{ secrets.VITE_BACKENDAPI_URL }} 

jobs:
  build:
    permissions:
        actions: write
        checks: write
        contents: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Build App
        run: pnpm run compile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: wd.r74.tech
